INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Ashford International', 'Folkestone Central');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Birmingham International', 'Birmingham New Street');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Birmingham International', 'Fort William');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Birmingham New Street', 'Wolverhampton');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Bletchley', 'Rugby');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Bristol Parkway', 'Bristol Temple Meads');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Bristol Temple Meads', 'Exeter St. Davids');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Clapham Junction', 'Staines');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Clapham Junction', 'Wimbledon');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Coulsdon South', 'Gatwick Airport');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Coventry', 'Birmingham International');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Coventry', 'Nuneaton');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Coventry', 'Oxford');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Donauwörth', 'München Hauptbahnhof');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('East Croydon', 'Coulsdon South');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('East Croydon', 'Sanderstead');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Ebbsfleet International', 'Ashford International');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Exeter St. Davids', 'Barnstaple');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Exeter St. Davids', 'Totnes');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Feldmoching', 'Flughafen München Besucherpark');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Flåm', 'Kjosfossen');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Flughafen München Besucherpark', 'Moosach');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Folkestone Central', 'Deal');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Giselastraße', 'Feldmoching');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Kjosfossen', 'Myrdal');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Bridge', 'Clapham Junction');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Bridge', 'Tonbridge');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Charing Cross', 'London Bridge');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Euston', 'Bletchley');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Liverpool Street', 'Stratford');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Paddington', 'Slough');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London St Pancras', 'Stratford International');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Victoria', 'East Croydon');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('London Waterloo', 'Clapham Junction');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Moosach', 'Olympiazentrum');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('München Hauptbahnhof', 'München Ost');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('München Ost', 'Flughafen München Besucherpark');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('München Ost', 'Salzburg');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Nantes', 'Saint-Gilles-Croix-de-Vie');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Norwich', 'Cambridge');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Norwich', 'Hoveton & Wroxham');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Nuneaton', 'Peterborough');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Olympiazentrum', 'Giselastraße');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Peterborough', 'Norwich');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Reading', 'Reigate');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Reading', 'Swindon');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Rugby', 'Coventry');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Sanderstead', 'Upper Warlingham');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Slough', 'Twyford');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Slough', 'Windsor & Eton Riverside');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Stratford', 'Norwich');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Stratford International', 'Ebbsfleet International');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Swindon', 'Bath Spa');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Swindon', 'Bristol Parkway');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Telford Central', 'Shrewsbury');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Tonbridge', 'Ashford International');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Twyford', 'Reading');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Wimbledon', 'Kingston');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Wimbledon', 'Southampton Central');
INSERT INTO `train-journeys`.links (location_a, location_b) VALUES ('Wolverhampton', 'Telford Central');
